server:
  port: 8081
  servlet:
    context-path: /

spring:
  thymeleaf: #模板配置
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  devtools:  #热部署配置
    livereload:
      enabled: false
    restart:
      additional-paths: controller/src/main/java,dao/src/main/java,service/src/main/java,shiro/src/main/java
  datasource: #数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.118.152:3306/yh_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 30000
    tomcat:
      max-active: 20
      initial-size: 1
      validation-query: select 'x'
      min-idle: 1
  liquibase: #sql版本管理
    change-log: classpath:liquibase/master.yml
    user: root
    password:
    url: jdbc:mysql://47.107.118.152:3306/yh_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    drop-first: false
    enabled: true
  redis:   #redis配置
    host: 47.107.118.152
    port: 6379
    password:
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1



#实现springboot优雅关闭，通过命令：curl -X POST http://localhost:9001/manage/actuator/shutdown
management:
  server:
    servlet:
      context-path: /manage
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#mybatis配置
mybatis:
  mapper-locations: classpath*:com/yaohan/bbs/dao/mapper/xml/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

#打印mabitis sql 日志
logging:
  level:
    root: info
    org.mybatis: debug
    com.yaohan.bbs.dao: debug

#ID生成工具配置
id:
  worker: 1   #工作机器ID(0~31)，用于集群区分
  datacenter: 20  #数据中心ID(0~31)，用于区分不同数据集群
  app: yaohanbbs

#用户上传文件路径
upload:
  images-path: C:\Users\renti\Desktop\mybbsPic\
#首页置顶帖子数量
index.top.num: 5