server:
  port: 8081
  servlet:
    context-path: /

spring:
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  devtools:
    livereload:
      enabled: false
    restart:
      additional-paths: controller/src/main/java,dao/src/main/java,service/src/main/java,shiro/src/main/java
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.118.152:3306/yh_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 30000
    tomcat:
      max-active: 20
      initial-size: 1
      validation-query: select 'x'
      min-idle: 1
  liquibase:
    change-log: classpath:liquibase/master.yml
    user: root
    password:
    url: jdbc:mysql://47.107.118.152:3306/yh_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    drop-first: false
    enabled: true
  redis:
    host: 47.107.118.152
    port: 6379
    password:
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1



#实现springboot优雅关闭，通过命令：curl -X POST http://localhost:9001/manage/actuator/shutdown
management:
  server:
    servlet:
      context-path: /manage
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true


mybatis:
  mapper-locations: classpath*:com/yaohan/bbs/dao/mapper/xml/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  level:
    root: info
    org.mybatis: debug
    com.yaohan.bbs.dao: debug

id:
  worker: 1
  datacenter: 20
  app: yaohanbbs

upload:
  images-path: C:\Users\renti\Desktop\mybbsPic\